POST http://localhost:3003/api/blogs/
Content-Type: application/json Authorization: bearer
$2b$10$H7VTBGsFwqCBSGh8xkwVAOtGPJCUJeljbOkRGLuLEqo8aIyWKG28W

{
    "title": "Hessun mietinnät",
    "author": "Hessu Hopo",
    "url": "www.jee3.com",
    "likes": 22,
    "userId": "603d5a234b7799421fea50e9"
}