POST http://localhost:3003/api/blogs/
Content-Type: application/json Authorization: bearer
$2b$10$XNKKJdZCvE7RNbUKq7Gd3.cwxGrYESipaunCUBFhuBcBnKqErzbZ6

{
    "title": "Hessun mietinnät",
    "author": "Hessu Hopo",
    "url": "www.jee3.com",
    "likes": 22,
    "userId": "6037b712fc143936f47fde14"
}