POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Hessun mietinnät",
    "author": "Hessu Hopo",
    "url": "www.jee3.com",
    "likes": 22,
    "userId": "60342211a2af4d40be568c90"
}